# Site settings
title: Dolomites Labs - Design & Software
email: dolomiteslabs@gmail.com
url: http://dolomiteslabs.com
description: "Il tuo Team per la creazione di siti internet, design di interni, design grafico, sviluppo software e applicazioni, fotografia ritratti, ceremonie e interni."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00A096 #80B3FF
  secondary: 3e3d40 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dolomites Labs
  location: Location
  social: Social
  credits: Contacts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: instagram
    url: http://stackoverflow.com/questions/tagged/jekyll
  

# Postal address (add as many lines as necessary)
address:
  - line: Val di Fiemme
  - line: Italy

# Credits content
credits: <a href="mailto:dolomiteslabs@gmail.com">dolomiteslabs@gmail.com</a>

mobile: Stefano +39 3406735250<br>Gaia +39 3486030905
# <a href="tel:+393406735250> 
# <br><a href="tel:+393486030905>Gaia +39 3486030905</a>

# Build settings
markdown: kramdown
permalink: pretty
