# Site settings
title: Dolomites Labs | Design & Software
email: dolomiteslabs@gmail.com
url: http://dolomiteslabs.com
description: "Il tuo Team per la creazione e lo sviluppo di siti internet moderni e responsive. Design di interni con rilievi, studi in pianta e render fotorealistici. Design grafico moderno, loghi, brand identity e immagini coordinate come flyer, brochures e volantini. Sviluppo Software e Applicazioni Android iOS Windows Phone. Fotografia servizi fotografici per privati come ritratti,  matrimoni, battesimi, bambini, interni e per aziende(hotel,negozi)."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00A096 #80B3FF
  secondary: 3e3d40 #FD6E8A
  secondary-dark: 233140 #A2122F
  

# Footer settings
footer:
  copyright: Dolomites Labs
  location: Location
  social: Social
  credits: Contacts
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/dolomiteslabs
  
  

# Postal address (add as many lines as necessary)
address:
  - line: Val di Fiemme
  - line: Italy
footerimg: "img/footer-img.png"
# Credits content
credits: <a href="mailto:dolomiteslabs@gmail.com">dolomiteslabs@gmail.com</a>

mobile: Stefano +39 3406735250<br>Gaia +39 3486030905
# <a href="tel:+393406735250> 
# <br><a href="tel:+393486030905>Gaia +39 3486030905</a>

# Build settings
markdown: kramdown
permalink: pretty
