# Site settings
title: Dolomites Labs
email: dolomiteslabs@gmail.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Stefano Mich
  location: Location
  social: Social
  credits: Contacts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: instagram
    url: http://stackoverflow.com/questions/tagged/jekyll
  

# Postal address (add as many lines as necessary)
address:
  - line: Località Stava 5
  - line: Tesero, 38038 Italy

# Credits content
credits: <a href="dolomiteslabs@gmail.com">dolomiteslabs@gmail.com</a><br>+39 3406735250<br>+39 3486030905

# Build settings
markdown: kramdown
permalink: pretty
